scraping:
    base_url: "https://erowid.org/experiences/exp.cgi"
    delay_range: [1, 3] # seconds between requests
    max_retries: 3
    timeout: 10
    user_agents_rotate: true

data:
    target_reports: 200
    min_text_length: 100
    max_text_length: 10000

paths:
    raw_data: "data/raw"
    scraped_data: "data/scraped"
    processed_data: "data/processed"
